// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	DB: KVNamespace;
	SITE_BASE_URL: "";
	HTML_TO_IMG_RENDER_SERVICE: "";
	IMG_GENERATE_SERVICE: "";
	OPENAI_ORGANIZATION: "";
	OPENAI_PROJECT: "";
	OPENAI_APIKEY: "";
}
