name = "infinity-book-pet-heroes"
compatibility_date = "2024-09-29"
pages_build_output_dir = "./dist/cloudflare"
compatibility_flags = [ "nodejs_compat_v2" ]
#workers_dev = true

[[kv_namespaces]]
binding = "DB"
id = "5c45d40ba30745e5b1ad4c8de9ba9d72"

[vars]
SITE_BASE_URL = ""
HTML_TO_IMG_RENDER_SERVICE = ""
IMG_GENERATE_SERVICE = ""
OPENAI_ORGANIZATION = ""
OPENAI_PROJECT = ""
OPENAI_APIKEY = ""

